/**
 * Created by Administrator on 2017/12/2.
 */
var data=[
    [
        "ITEMimg/i1/ITEM.jpg",
        "ITEMimg/i1/1.png",
        "ITEMimg/i1/2.png",
        "ITEMimg/i1/3.png",
        "ITEMimg/i1/4.png",
        "ITEMimg/i1/5.png",
        "ITEMimg/i1/6.png",
        "ITEMimg/i1/7.png"
    ],
    [
        "ITEMimg/i2/ietm.jpg",
        "ITEMimg/i2/1.png",
        "ITEMimg/i2/2.png",
        "ITEMimg/i2/3.png",
        "ITEMimg/i2/4.png"
    ],
    [
        "ITEMimg/i3/ITEM.jpg",
        "ITEMimg/i3/1.png",
        "ITEMimg/i3/2.png",
        "ITEMimg/i3/3.png",
        "ITEMimg/i3/4.png",
        "ITEMimg/i3/5.png",
        "ITEMimg/i3/6.png"
    ],
    [
        "ITEMimg/i4/ITEM.jpg",
        "ITEMimg/i4/1.png",
        "ITEMimg/i4/2.png",
        "ITEMimg/i4/3.png",
        "ITEMimg/i4/4.png",
        "ITEMimg/i4/5.png"
    ],
    [
        "ITEMimg/i5/ITEM.jpg",
        "ITEMimg/i5/1.png",
        "ITEMimg/i5/2.png",
        "ITEMimg/i5/3.png",
        "ITEMimg/i5/4.png",
        "ITEMimg/i5/5.png"
    ],
    [
        "ITEMimg/i6/ITEM.jpg",
        "ITEMimg/i6/1.png",
        "ITEMimg/i6/2.png",
        "ITEMimg/i6/3.png",
        "ITEMimg/i6/4.png",
        "ITEMimg/i6/5.png",
        "ITEMimg/i6/6.png",
        "ITEMimg/i6/7.png",
        "ITEMimg/i6/8.png",
        "ITEMimg/i6/9.png"
    ]
];
var whxyInfo=[
    [
        {    //1
            x:10,
            y:39,
            w:488,
            h:365
        },
        {         //2
            x:113,
            y:87,
            w:187,
            h:140
        },
        {   //3
            x:309,
            y:90,
            w:130,
            h:129
        },
        {      //4
            x:23,
            y:255,
            w:56,
            h:75
        },
        {       //5
            x:197,
            y:265,
            w:55,
            h:75
        },
        {     //6
            x:3,
            y:357,
            w:292,
            h:83
        },
        {     //7
            x:86,
            y:292,
            w:392,
            h:170
        }
    ],
    [
        {
            x:117,
            y:120,
            w:114,
            h:112
        },
        {
            x:86,
            y:98,
            w:333,
            h:225
        },
        {
            x:283,
            y:202,
            w:94,
            h:92
        },
        {
            x:191,
            y:325,
            w:130,
            h:72
        }
    ],
    [
        {    //1
            x:64,
            y:129,
            w:408,
            h:178
        },
        {    //2
            x:91,
            y:172,
            w:74,
            h:46
        },
        {    //3
            x:239,
            y:96,
            w:139,
            h:61
        },
        {    //4
            x:433,
            y:180,
            w:59,
            h:34
        },
        {    //5
            x:212,
            y:235,
            w:219,
            h:165
        },
        {    //6
            x:28,
            y:226,
            w:51,
            h:73
        }
    ],
    [
        {
            w:308,//1
            h:155,
            x:86,
            y:3
        },
        {
            w:319,//3
            h:114,
            x:80,
            y:107
        },
        {
            w:311,//2
            h:110,
            x:87,
            y:178
        },
        {
            w:250,//4
            h:100,
            x:132,
            y:252
        },
        {
            w:71,//5
            h:62,
            x:328,
            y:341
        }
    ],
    [
        {
            w:218,//1
            h:221,
            x:69,
            y:4
        },
        {
            w:48,//2
            h:58,
            x:161,
            y:71
        },
        {
            w:91,//3
            h:77,
            x:7,
            y:97
        },
        {
            w:435,//4
            h:277,
            x:62,
            y:220
        },
        {
            w:338,//5
            h:183,
            x:124,
            y:253
        }
    ],
    [
        {
            w:138,//1
            h:40,
            x:173,
            y:3
        },
        {
            w:220,//2
            h:134,
            x:23,
            y:21
        },
        {
            w:234,//3
            h:304,
            x:3,
            y:90
        },
        {
            w:247,//4
            h:347,
            x:54,
            y:147
        },
        {
            w:211,//5
            h:318,
            x:218,
            y:179
        },
        {
            w:127,//6
            h:296,
            x:371,
            y:131
        },
        {
            w:119,//7
            h:140,
            x:376,
            y:72
        },
        {
            w:104,//8
            h:61,
            x:312,
            y:12
        },
        {
            w:176,//9
            h:144,
            x:220,
            y:39
        }
    ]
];