document.writeln("<script language=\'javascript\'>");
document.writeln("");
document.writeln("");
document.writeln("var nums;");
document.writeln("nums=0;");
document.writeln("");
document.writeln("$DE(\'mores\').disabled = false;");
document.writeln("function PostComment()");
document.writeln("{	");
document.writeln("		var f = document.feedback;		");
document.writeln("		if(f.w.value==\'\') {");
document.writeln("				alert(\"请输入所藏内容！\");");
document.writeln("				return;");
document.writeln("			}");
document.writeln("			");
document.writeln("			");
document.writeln("		if(f.num) {");
document.writeln("			for(var i=0; i < f.num.length; i++)");
document.writeln("				if(f.num[i].checked) num = f.num[i].value;");
document.writeln("		}");
document.writeln("		");
document.writeln("		if(f.yayuntype) {");
document.writeln("			for(var i=0; i < f.yayuntype.length; i++)");
document.writeln("				if(f.yayuntype[i].checked) yayuntype = f.yayuntype[i].value;");
document.writeln("		}");
document.writeln("		");
document.writeln("		if(f.type) {");
document.writeln("			for(var i=0; i < f.type.length; i++)");
document.writeln("				if(f.type[i].checked) type = f.type[i].value;");
document.writeln("		}");
document.writeln("		");
document.writeln("		");
document.writeln("		");
document.writeln("		var taget_obj = $DE(\'shi\');");
document.writeln("		");
document.writeln("		");
document.writeln("		var waithtml = \"<div style=\'line-height:30px\'><img src=\'loadinglit.gif\' />正在发送中...</div>\";		");
document.writeln("		var myajax = new DedeAjax(taget_obj, false, true, \'\', \'\', waithtml);");
document.writeln("		myajax.sendlang = \'gb2312\';");
document.writeln("		myajax.AddKeyN(\'w\', f.w.value);");
document.writeln("		myajax.AddKeyN(\'num\', num);");
document.writeln("		");
document.writeln("		myajax.AddKeyN(\'type\', type);");
document.writeln("		myajax.AddKeyN(\'yayuntype\', yayuntype);");
document.writeln("		myajax.SendGet(\'fasong.php\');");
document.writeln("		f.w.value=f.w.value+\" \";");
document.writeln("		//$DE(\'mores\').innerHTML=\"再来一首\";");
document.writeln("		//nums=nums+1;");
document.writeln("		//if(nums==7){$nums=0;}");
document.writeln("		$DE(\'mores\').disabled = \"disabled\";");
document.writeln("		$DE(\'mores\').value = \"再来一首\";");
document.writeln("		$DE(\'shuom\').innerHTML = \"(3秒后)\";");
document.writeln("		");
document.writeln("		//var i = 3;");
document.writeln("		window.setTimeout(");
document.writeln("	function() {");
document.writeln("		");
document.writeln("			//$DE(\'mores\').value = \'生成\';");
document.writeln("			$DE(\'mores\').disabled = false;");
document.writeln("			$DE(\'mores\').value = \"再来一首\";");
document.writeln("			$DE(\'shuom\').innerHTML = \"\";");
document.writeln("		");
document.writeln("			//$DE(\'mores\').disabled = true;");
document.writeln("			//$DE(\'mores\').value = \'生成(\'+i+\')\';");
document.writeln("			//$DE(\'mores\').disabled = \"disabled\";");
document.writeln("			");
document.writeln("			");
document.writeln("		");
document.writeln("		//}");
document.writeln("	}, ");
document.writeln("3000)");
document.writeln("		");
document.writeln("		//return 1;		");
document.writeln("		");
document.writeln("}");
document.writeln("</script>");